require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PartCompaniesController do

  # This should return the minimal set of attributes required to create a valid
  # PartCompany. As you add validations to PartCompany, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all part_companies as @part_companies" do
      part_company = PartCompany.create! valid_attributes
      get :index
      assigns(:part_companies).should eq([part_company])
    end
  end

  describe "GET show" do
    it "assigns the requested part_company as @part_company" do
      part_company = PartCompany.create! valid_attributes
      get :show, :id => part_company.id
      assigns(:part_company).should eq(part_company)
    end
  end

  describe "GET new" do
    it "assigns a new part_company as @part_company" do
      get :new
      assigns(:part_company).should be_a_new(PartCompany)
    end
  end

  describe "GET edit" do
    it "assigns the requested part_company as @part_company" do
      part_company = PartCompany.create! valid_attributes
      get :edit, :id => part_company.id
      assigns(:part_company).should eq(part_company)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new PartCompany" do
        expect {
          post :create, :part_company => valid_attributes
        }.to change(PartCompany, :count).by(1)
      end

      it "assigns a newly created part_company as @part_company" do
        post :create, :part_company => valid_attributes
        assigns(:part_company).should be_a(PartCompany)
        assigns(:part_company).should be_persisted
      end

      it "redirects to the created part_company" do
        post :create, :part_company => valid_attributes
        response.should redirect_to(PartCompany.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved part_company as @part_company" do
        # Trigger the behavior that occurs when invalid params are submitted
        PartCompany.any_instance.stub(:save).and_return(false)
        post :create, :part_company => {}
        assigns(:part_company).should be_a_new(PartCompany)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        PartCompany.any_instance.stub(:save).and_return(false)
        post :create, :part_company => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested part_company" do
        part_company = PartCompany.create! valid_attributes
        # Assuming there are no other part_companies in the database, this
        # specifies that the PartCompany created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        PartCompany.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => part_company.id, :part_company => {'these' => 'params'}
      end

      it "assigns the requested part_company as @part_company" do
        part_company = PartCompany.create! valid_attributes
        put :update, :id => part_company.id, :part_company => valid_attributes
        assigns(:part_company).should eq(part_company)
      end

      it "redirects to the part_company" do
        part_company = PartCompany.create! valid_attributes
        put :update, :id => part_company.id, :part_company => valid_attributes
        response.should redirect_to(part_company)
      end
    end

    describe "with invalid params" do
      it "assigns the part_company as @part_company" do
        part_company = PartCompany.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PartCompany.any_instance.stub(:save).and_return(false)
        put :update, :id => part_company.id, :part_company => {}
        assigns(:part_company).should eq(part_company)
      end

      it "re-renders the 'edit' template" do
        part_company = PartCompany.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PartCompany.any_instance.stub(:save).and_return(false)
        put :update, :id => part_company.id, :part_company => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested part_company" do
      part_company = PartCompany.create! valid_attributes
      expect {
        delete :destroy, :id => part_company.id
      }.to change(PartCompany, :count).by(-1)
    end

    it "redirects to the part_companies list" do
      part_company = PartCompany.create! valid_attributes
      delete :destroy, :id => part_company.id
      response.should redirect_to(part_companies_url)
    end
  end

end
